// Code generated by mockery v2.33.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	todo "github.com/sukha-id/bee/internal/domain/todo"
)

// TodoUseCase is an autogenerated mock type for the TodoUseCase type
type TodoUseCase struct {
	mock.Mock
}

// StoreOne provides a mock function with given fields: ctx, _a1
func (_m *TodoUseCase) StoreOne(ctx context.Context, _a1 todo.Task) (todo.Task, error) {
	ret := _m.Called(ctx, _a1)

	var r0 todo.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, todo.Task) (todo.Task, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, todo.Task) todo.Task); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(todo.Task)
	}

	if rf, ok := ret.Get(1).(func(context.Context, todo.Task) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTodoUseCase creates a new instance of TodoUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTodoUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *TodoUseCase {
	mock := &TodoUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
