version: '3'
services:
  app:
    container_name: ${CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:8080"
    volumes:
      - "${LOG_DIR}:/go/src/app/log"
    environment:
      - "TZ=${TIMEZONE}"
    restart: unless-stopped