version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:8080"
    volumes:
      - "${LOG_DIR}:/log"
      - "./config.yaml:/app/config.yaml"
    environment:
      - "TZ=${TIMEZONE}"
      - "APP_COMMAND=${APP_COMMAND}"
    restart: unless-stopped