app:
  debug: true
  port: 8080
  timeout: 5
  secret_key: xxx
authentication:
  jwt:
    secret_key: xxx
    expired: 1 # in hour
mysql_db:
  hostname: localhost
  port: 3306
  username: root
  password: xxx
  database_name: xxx
  max_idle_connection: 10
  max_open_connection: 100
  max_lifetime_connection: 600
mongo_db:
  hostname: localhost
  port: 27017
  username: root
  password: xxx
  database_name: xxx
  max_idle_connection: 10
  max_open_connection: 100
  max_lifetime_connection: 600
log:
  dir: log # Don't Edit This
  file_name: xxx
  max_size: 4 # MB with min 1 MB
  local_time: true
  compress: true